version: '3.3'
services:
  db:
    image: postgresql
    restart: always
    environment:
      MYSQL_DATABASE: 'cotacao'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'postgres'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: